### ISSUE TITLE
Failed jobs not appearing as failed in UI

### ISSUE THREAD

**Issue by Gianlucamacis** [LlmLaraHub/larallama#10]
After uploading documents, the job appears to fail when in the admin panel is still loading for the user

User screen:
![CleanShot 2024-04-26 at 17 59 41](https://github.com/LlmLaraHub/laralamma/assets/14819507/89dea739-fe47-47c3-a10d-7a6f61e471bd)

Admin screen:
![CleanShot 2024-04-26 at 18 00 57](https://github.com/LlmLaraHub/laralamma/assets/14819507/73a3d0c7-82eb-49ca-a9e8-89fdbc313d92)

Ask
* Failed jobs to be marked as failed
* Failed jobs to be hidden by a filter after x number of hours/24 hours so that the list feels more like a document repository for the end user.

**Comment by alnutile** [comment]
Should be working now thanks!
