### ISSUE TITLE
Filesize error handling on upload

### ISSUE THREAD

**Issue by Gianlucamacis** [LlmLaraHub/larallama#11]
When uploading a file that's too large I get a PHP error message. IDeally there would be a friendlier error message as part of the UI. 

Of course even better would be to have a much higher limit so that i can drop in over 50 files in one go and let it run in the background :)

![CleanShot 2024-04-26 at 18 10 13](https://github.com/LlmLaraHub/laralamma/assets/14819507/27154bb2-30d2-4f88-a11c-974faa75117b)

**Comment by alnutile** [comment]
Add try catch
